# Generated by Django 5.0.2 on 2024-02-25 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codesubmission',
            name='user',
        ),
    ]
